# Descriptive statistics of JSS16 paper

> Reginaldo K Fukuchi  
> [Laboratory of Biomechanics and Motor Control](http://pesquisa.ufabc.edu.br/bmclab/)  
> Federal University of ABC, Brazil

This notebook calculates the descriptive statistics of the flexibility and strength measures grouped by intervention group and condition of the Fukuchi et al. (2016) paper. Part of these values were presented in Table 2 of the aforementioned manuscript.

## Abbreviations list
* HADD_FX: Hip Adduction flexibility 
* AGAS_FX: Gastrocnemius flexibility 
* ASOL_FX: Soleus flexibility 
* HER_FX: Hip ER flexibility 
* HIR_FX: Hip IR flexibility 
* HABD_ST: Hip abductors strength
* HEXT_ST: Hip extensors strength
* APF_ST: Ankle PF strength
* STG: Strengthening group
* FXG: Flexibility group
* CTG: Control group
* PRE: Pre-intervention measure
* POS: Post-intervention measure

## Setup environment

In [1]:
import os
import numpy as np
import pandas as pd

## Import file with data from each participant included in the study

In [2]:
path2 = '..\data'
filename = os.path.join(path2,'data.csv')
df = pd.read_csv(filename,index_col=0)

In [3]:
df.head()

,HADD_FX,AGAS_FX,ASOL_FX,HER_FX,HIR_FX,HABD_ST,HEXT_ST,APF_ST,Group,Condition
0,-25.7,100.0,104.0,40.0,50.0,33.526012,23.506744,35.452794,STG,PRE
1,-21.5,81.0,90.0,23.0,33.0,47.784200,38.005780,49.662813,STG,POS
2,-11.0,95.0,104.0,40.0,45.0,31.701031,11.759021,33.462199,STG,PRE
3,-31.7,85.0,89.0,29.0,30.0,23.322684,17.287895,28.186013,STG,POS
4,-31.4,88.0,92.0,33.0,41.0,26.709863,26.853852,42.872570,STG,PRE

In [4]:
df.tail()

,HADD_FX,AGAS_FX,ASOL_FX,HER_FX,HIR_FX,HABD_ST,HEXT_ST,APF_ST,Group,Condition
177,-29.9,90.0,100.0,33.0,39.0,26.224874,15.923367,39.991625,CTG,POS
178,-24.1,90.0,100.0,42.0,43.0,29.492861,14.069424,24.273757,CTG,PRE
179,-29.2,87.0,96.0,30.0,41.0,24.574050,9.796855,30.504587,CTG,POS
180,-23.7,84.0,87.0,38.0,38.0,29.125000,20.791667,37.875000,CTG,PRE
181,-30.2,93.0,99.0,42.0,42.0,24.835742,11.081910,35.676741,CTG,POS

## Descriptive stats

In [5]:
pd.set_option('precision', 2)
print('Descriptive stats of clinical vars grouped by intervention group and conditions (mean and std):')
df.groupby(['Group','Condition'])[df.columns.tolist()].agg([np.mean, np.std])

Descriptive stats of clinical vars grouped by intervention group and conditions (mean and std):

                HADD_FX       AGAS_FX       ASOL_FX       HER_FX       HIR_FX  \
                   mean   std    mean   std    mean   std   mean   std   mean
Group Condition
CTG   POS        -28.99  2.57   92.22  5.14   99.85  5.26  35.15  4.59  38.70
      PRE        -26.09  3.72   89.56  5.51   96.56  6.06  36.44  6.70  35.56
FXG   POS        -29.23  3.24   91.26  5.09   99.77  4.95  34.87  5.02  38.32
      PRE        -27.57  4.04   89.52  4.71   98.77  5.61  35.23  6.71  35.32
STG   POS        -29.09  3.61   90.33  5.42   99.42  6.15  33.82  4.81  35.82
      PRE        -26.34  3.91   88.06  4.68   96.06  4.67  35.58  5.23  35.76

                      HABD_ST       HEXT_ST       APF_ST
                  std    mean   std    mean   std   mean   std
Group Condition
CTG   POS        7.04   30.38  6.65   20.38  6.74  40.36  7.46
      PRE        7.46   30.16  4.81   22.79  5.10  35.23  6.69
FXG   POS        6.10   29.28  6.53   20.34  5.90  38.26  8.59
      PRE        6.99   30.94  5.92   24.08  6.59  38.28  8.66
STG   POS        6.21   31.44  5.49   21.18  5.19  41.53  8.05
      PRE        7.07   31.56  4.95   23.69  6.68  37.65  6.77

## References
* Fukuchi, R. K., Stefanyshyn, D. J., Stirling, L., & Ferber, R. (2016). Effects of strengthening and stretching exercise programmes on kinematics and kinetics of running in older adults: a randomised controlled trial. Journal of sports sciences, 34(18), 1774-1781.